name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Kiuwan Baseline Analysis
      uses: lsacera/KiuwanBaselineAction@v0.4
      with:
         # Name of Kiuwan project
         project: pepe
         # Label of the analysis
         label: github  
         # Username for kiuwan platform
         userid: ${{ secrets.KIUWAN_USER }}
         # Password for kiuwan platform
         password: ${{ secrets.KIUWAN_PASS }}
